apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example

spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  haproxy
                port:
                  name: http
