apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: haproxy

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: haproxy-config
    files:
      - configs/haproxy.cfg
